import '@style/global.css'

export const metadata = {
  title: 'Youtube Downloader',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <div className="main">
          <div className="gradient"></div>
        </div>

        <main>
          <div className="app">
            {children}
          </div>

        </main>
      </body>
    </html>
  )
}
